/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.TaiKhoan;
import service.TaiKhoanService;
import java.sql.*;

/**
 *
 * @author hodangquan
 */
public class DangKiForm extends javax.swing.JFrame {

    /**
     * Creates new form DangKiForm
     */
    TaiKhoanService taiKhoanService;
    public DangKiForm() {
        initComponents();
        
        taiKhoanService = new TaiKhoanService();
        
    }
    public TaiKhoan layTT(){
        String hoVaTen = txtHoVaTen.getText();
        String matKhau = String.valueOf(txtMatKhau.getPassword());
        String tenTK = txtTenTK.getText();
        String email = txtEmail.getText();
        return new TaiKhoan(tenTK,matKhau,hoVaTen,email);
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDangKi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnDong = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtHoVaTen = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        txtXacNhanMK = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDangKi.setText("Đăng Kí");
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Đăng Kí");

        jLabel2.setText("Tên TK");

        txtTenTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTKActionPerformed(evt);
            }
        });

        jLabel3.setText("Mật Khẩu");

        jLabel4.setText("Xác Nhận MK");

        jLabel5.setText("Email");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jLabel6.setText("Họ và Tên");

        txtHoVaTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoVaTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(btnDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDong))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(18, 18, 18))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(12, 12, 12)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtTenTK, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                    .addComponent(txtMatKhau)))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtXacNhanMK)
                                    .addGap(6, 6, 6))))))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtXacNhanMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangKi)
                    .addComponent(btnDong))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        // TODO add your handling code here:
        String hoVaTen = txtHoVaTen.getText().trim();
        String tenTK = txtTenTK.getText().trim();
        String matKhau = String.valueOf(txtMatKhau.getPassword()).trim();
        String xacNhanMK = String.valueOf(txtXacNhanMK.getPassword()).trim();
        String mail = txtEmail.getText().trim();
        
        String checkChu = "^[0-9]*$";
        String check = "^[a-zA-Z0-9]*$";
        String check1 = "^[a-z0-9]*$";
        String checkMail = "^([a-zA-Z0-9]+\\.)*[a-zA-Z0-9]+@([a-z]+\\.)+[a-z]{2,4}$";
        String check3 = "(?=.*[A-Z]).*$";

        
        if(hoVaTen.isEmpty() || tenTK.isEmpty() || matKhau.isEmpty() || xacNhanMK.isEmpty() || mail.isEmpty()){
           JOptionPane.showMessageDialog(this, "Chắc là không được để trống đâu :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        
        if(hoVaTen.matches(checkChu)){
            JOptionPane.showMessageDialog(this, "Chắc Tên phải là chữ rồi  :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        if(tenTK.replaceAll("[^ ]", "").length() > 0){
            JOptionPane.showMessageDialog(this, "Tên Tài Khoản chắc là không được để toàn khoảng trắng đâu :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        if(matKhau.replaceAll("[^ ]", "").length() > 0){
            JOptionPane.showMessageDialog(this, "Mật khẩu chắc là không được để toàn khoảng trắng đâu :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        if(mail.replaceAll("[^ ]", "").length() > 0){
            JOptionPane.showMessageDialog(this, "Email chắc là không được để toàn khoảng trắng đâu :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        if(matKhau.length()<8 || matKhau.length()>16){
            JOptionPane.showMessageDialog(this, "Chắc là Mật Khẩu chỉ được nhập từ 8 - 16 ký tự thôi :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        if(!matKhau.equals(xacNhanMK)){
            JOptionPane.showMessageDialog(this, "Chắc là Mật Khẩu và Xác Nhân Mất khẩu không khớp rồi :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        
        if(!matKhau.matches(check)){
            JOptionPane.showMessageDialog(this, "Chắc là Mật Khẩu không được chứa kí tự đặc biệt rồi :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        if(!matKhau.matches(check3)){
            JOptionPane.showMessageDialog(this, "Chắc là Mật Khẩu Phải kèm cả kí tự hoa rồi :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
//        if(!matKhau.matches(check1)){
//            JOptionPane.showMessageDialog(this, "Chắc là Mật Khẩu không được chứa kí tự viết hoa rồi :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
//                return;
//        }
        if(!mail.matches(checkMail)){
            JOptionPane.showMessageDialog(this, "Này này :(( , Chỉ được phép dùng các chữ cái (a -> z), số (0 -> 9), và dấu chấm (.) :)) /n"
                    + "Dịnh dạng Example@gmail.con", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        if(hoVaTen.equals(tenTK)){
            JOptionPane.showMessageDialog(this, "Chắc là Họ và Tên không được giống Tên Tài Khoản rồi  :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        if(hoVaTen.length() > 40){
            JOptionPane.showMessageDialog(this, "Chắc là Họ và Tên không được vượt quá 40 kí tự rồi  :))", "Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
        }
        
        try {
            
            TaiKhoan taiKhoan = layTT();
                    
            
            if(taiKhoanService.checkUesrnametontai(taiKhoan.getTenTK()) == false){
                JOptionPane.showMessageDialog(this, "Chắc Tên Tài Khoản đã tồn tại :))");
                return;
            }
            if(taiKhoanService.them(taiKhoan) == false){
                JOptionPane.showMessageDialog(this, " Chắc là đăng kí Thất Bại rồi :))");
                return;
            }
            JOptionPane.showMessageDialog(this, " Chắc là đăng kí Thành Công rồi :))");
            txtHoVaTen.setText("");
            txtTenTK.setText("");
            txtMatKhau.setText("");
            txtXacNhanMK.setText("");
            txtEmail.setText("");
            
            } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnDangKiActionPerformed

    private void txtTenTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTKActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
        String checkMail = "^([a-zA-Z0-9]+\\.)*[a-zA-Z0-9]+@([a-z]+\\.)+[a-z]{2,4}$";
        if(txtEmail.getText().matches(checkMail)){
            return;
        }
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void txtHoVaTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoVaTenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtHoVaTenActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKi;
    private javax.swing.JButton btnDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenTK;
    private javax.swing.JPasswordField txtXacNhanMK;
    // End of variables declaration//GEN-END:variables
}
